### ISSUE TITLE
appim tries to remove cache directory

### ISSUE THREAD

**Issue by ListeriaM** [WalkingGarbage/appim#1]
https://github.com/WalkingGarbage/appim/blob/b6aff155b0b87d93c79e2a801078dc04f1af2007/appim.sh#L128
this will clear the cache of every application when `XDG_CACHE_HOME` is not set.

since `tempdir` is just used for temporary files (and not for cache) I suggest:
```diff
28,32c28,29
< if [[ ! -z "$XDG_CACHE_HOME" ]]; then
<   tempdir="$XDG_CACHE_HOME/appim"
< else
<   tempdir="$HOME/.cache"
< fi
---
> tempdir="$(mktemp -dt appim.XXXXXX)"
> trap "rm -rf '$tempdir'" HUP INT QUIT ILL TRAP BUS TERM
```

**Comment by fralnz** [comment]
@nacho-dz Hi, thank you for your suggestion. I tested it and it works perfectly, I didn't know about mktemp.
Is there a way I can credit you? I don't know much about GitHub so I'm not really sure how to implement this without patching the code manually.

**Comment by ListeriaM** [comment]
there's no need, if you'd like I can make a PR though

**Comment by fralnz** [comment]
@nacho-dz fair enough, please do a PR
